#cloud-config

package_upgrade: true

packages:
  - PyYAML
  - apr
  - apr-util
  - autoconf
  - autogen-libopts
  - automake
  - avahi-libs
  - bind-libs
  - bind-utils
  - bison
  - boost-system
  - boost-thread
  - byacc
  - bzip2
  - cloud-utils
  - cpp
  - cscope
  - ctags
  - dhcp
  - diffstat
  - doxygen
  - dwz
  - dyninst
  - ebtables
  - elfutils
  - emacs-filesystem
  - epel-release
  - euca2ools
  - fail2ban-sendmail
  - fail2ban-server
  - flex
  - fuse
  - fuse-devel
  - fuse-libs
  - gcc
  - gcc-c++
  - gcc-gfortran
  - gdb
  - gdisk
  - gettext-common-devel
  - gettext-devel
  - git
  - glib-networking
  - glibc-devel
  - glibc-headers
  - glusterfs
  - glusterfs-api
  - glusterfs-client-xlators
  - glusterfs-libs
  - gperftools-libs
  - gpg-pubkey
  - gpg-pubkey
  - gpm-libs
  - indent
  - intltool
  - ipset
  - ipset-libs
  - iptables-services
  - iptables-utils
  - iwl7265-firmware
  - kernel-devel
  - kernel-headers
  - libaio
  - libdwarf
  - libgfortran
  - libgnome-keyring
  - libicu
  - libiscsi
  - libmpc
  - libquadmath
  - libquadmath-devel
  - librados2
  - librbd1
  - libstdc++-devel
  - libtomcrypt
  - libtommath
  - libtool
  - libunwind
  - libxslt
  - linux-firmware
  - m4
  - mokutil
  - mpfr
  - neon
  - net-tools
  - nspr-devel
  - nss-devel
  - nss-softokn-devel
  - nss-softokn-freebl-devel
  - nss-util-devel
  - ntp
  - ntpdate
  - pakchois
  - patch
  - patchutils
  - perl
  - perl-Carp
  - perl-Data-Dumper
  - perl-Encode
  - perl-Error
  - perl-Exporter
  - perl-File-Path
  - perl-File-Temp
  - perl-Filter
  - perl-Getopt-Long
  - perl-Git
  - perl-HTTP-Tiny
  - perl-PathTools
  - perl-Pod-Escapes
  - perl-Pod-Perldoc
  - perl-Pod-Simple
  - perl-Pod-Usage
  - perl-Scalar-List-Utils
  - perl-Socket
  - perl-Storable
  - perl-TermReadKey
  - perl-Test-Harness
  - perl-Text-ParseWords
  - perl-Thread-Queue
  - perl-Time-HiRes
  - perl-Time-Local
  - perl-XML-Parser
  - perl-constant
  - perl-libs
  - perl-macros
  - perl-parent
  - perl-podlators
  - perl-srpm-macros
  - perl-threads
  - perl-threads-shared
  - python-IPy
  - python-ldap
  - python-lxml
  - python-paramiko
  - python-perf
  - python-progressbar
  - python-pyasn1
  - python-requestbuilder
  - python-slip
  - python-slip-dbus
  - python2-boto
  - python2-crypto
  - python2-ecdsa
  - python2-rsa
  - qemu-guest-agent
  - qemu-img
  - rcs
  - redhat-rpm-config
  - rpm-build
  - rpm-sign
  - rsyslog-mmjsonparse
  - screen
  - subversion
  - subversion-libs
  - swig
  - systemd-python
  - systemtap
  - systemtap-client
  - systemtap-devel
  - systemtap-runtime
  - tcsh
  - tmux
  - unzip
  - vim-common
  - vim-enhanced
  - vim-filesystem
  - zip
  - zsh
