#cloud-config

package_upgrade: true

bootcmd:
  - yum install -y epel-release

write_files:
  - path: /tmp/linux-rootfs-resize.sh
    content: |
        #! /bin/bash
        cd /tmp
        git clone https://github.com/flegmatik/linux-rootfs-resize.git
        cd linux-rootfs-resize
        ./install
    permissions: '0744'

runcmd:
  - /tmp/linux-rootfs-resize.sh 

packages:
  - "@Development Tools"
  - qemu-guest-agent
  - python-virtualenv
  - python-pip
  - cmake
  - wget
  - emacs-nox
  - parted
  - cloud-utils
  

