#cloud-config

package_upgrade: true
package_reboot_if_required: true

yum_repos:
  epel:
    baseurl: "http://ftp.ussg.iu.edu/linux/epel/6/x86_64/"
    enabled: true
    gpgcheck: true
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6"
    name: "Extra Packages for Enterprise Linux 6 - $basearch"

write_files:
  - path: /tmp/linux-rootfs-resize.sh
    content: |
        #! /bin/bash
        cd /tmp
        git clone https://github.com/flegmatik/linux-rootfs-resize.git
        cd linux-rootfs-resize
        ./install
    permissions: '0744'

runcmd:
  - /tmp/linux-rootfs-resize.sh 
  - sysctl -w net.core.netdev_max_backlog=300000
  - sysctl -w 'net.ipv4.tcp_wmem=4096 87380 16777216'
  - sysctl -w 'net.ipv4.tcp_rmem=4096 87380 16777216'
  - sysctl -w net.core.wmem_max=16777216
  - sysctl -w net.core.rmem_max=16777216

packages:
  - "@Development Tools"
  - qemu-guest-agent
  - python-virtualenv
  - python-pip
  - cmake
  - wget
  - emacs-nox
  - parted
  - cloud-utils
  
power_state:
 mode: reboot
 timeout: 30
 condition: True

cloud_final_modules:
 - rightscale_userdata
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
 - power_state_change
