#cloud-config

package_upgrade: true
package_reboot_if_required: true

bootcmd:
  - yum install -y epel-release

write_files:
  - path: /tmp/linux-rootfs-resize.sh
    content: |
        #! /bin/bash
        cd /tmp
        git clone https://github.com/flegmatik/linux-rootfs-resize.git
        cd linux-rootfs-resize
        ./install
    permissions: '0744'

runcmd:
  - /tmp/linux-rootfs-resize.sh
  - sysctl -w net.core.netdev_max_backlog=300000
  - sysctl -w 'net.ipv4.tcp_wmem=4096 87380 16777216'
  - sysctl -w 'net.ipv4.tcp_rmem=4096 87380 16777216'
  - sysctl -w net.core.wmem_max=16777216
  - sysctl -w net.core.rmem_max=16777216
  - wget https://www.realvnc.com/download/file/vnc.files/VNC-5.3.2-Linux-x64-RPM.tar.gz -O /tmp/VNC-5.3.2-Linux-x64-RPM.tar.gz
  - tar zxvf /tmp/VNC-5.3.2-Linux-x64-RPM.tar.gz
  - yum install /root/VNC-Server-5.3.2-Linux-x64.rpm
packages:
  - "@Additional Development"
  - "@Desktop Debugging and Performance Tools"
  - "@Desktop"
  - "@Development tools"
  - "@Dial-up Networking Support"
  - "@Directory Client"
  - "@E-mail server"
  - "@Fonts"
  - "@General Purpose Desktop"
  - "@Graphical Administration Tools"
  - "@Guest Agents"
  - "@Internet Browser"
  - "@Legacy X Window System compatibility"
  - "@Milkymist"
  - "@Network Infrastructure Server"
  - "@Perl Support"
  - "@Security Tools"
  - "@System administration tools"
  - "@Web Server"
  - "@X Window System"
  - https://download1.rstudio.org/rstudio-0.99.903-x86_64.rpm
  - https://mran.revolutionanalytics.com/install/mro/3.3.0/MRO-3.3.0.el6.x86_64.rpm
  - nss_db
  - xorg-x11-drv-modesetting
  - xorg-x11-glamor
  - fail2ban
  - tcsh
  - tmpwatch
  - m2crypto
  - fuse-devel
  - python-simplejson
  - poppler-utils
  - foomatic-db-filesystem
  - dhcp
  - 
  - yum-utils
  - xterm
  - zsh
  - gnome-applets
  - gdm
  - cloud-utils-growpart
  - cloud-utils  
  - at
  - screen
  - gnome-screensaver
  - gnome-speech
  - gnome-mag
  - gnome-vfs2-smb
  - redhat-lsb-core
  - redhat-lsb-graphics


power_state:
 mode: reboot
 timeout: 30
 condition: True

cloud_final_modules:
 - rightscale_userdata
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
 - power_state_change
