#cloud-config

apt_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - aspell
  - aspell-en
  - autoconf
  - automake
  - autotools-dev
  - fail2ban
  - firefox
  - glib-networking-common
  - glib-networking-services
  - glib-networking:amd64
  - gnome-icon-theme
  - gnome-icon-theme-full
  - gsettings-desktop-schemas
  - gtk2-engines-murrine:amd64
  - gtk2-engines-pixbuf:amd64
  - hddtemp
  - isc-dhcp-server
  - language-pack-en
  - language-pack-en-base
  - libaspell15
  - libburn4
  - libdbusmenu-glib4:amd64
  - libdbusmenu-gtk4:amd64
  - libfam0
  - libfile-basedir-perl
  - libfile-desktopentry-perl
  - libfile-mimeinfo-perl
  - libgtksourceview2.0-0
  - libgtksourceview2.0-common
  - libisofs6
  - libjs-jquery
  - libjte1
  - libopts25:amd64
  - libpango1.0-0:amd64
  - libpangox-1.0-0:amd64
  - libpangoxft-1.0-0:amd64
  - libprotobuf8:amd64
  - libproxy1:amd64
  - libpthread-stubs0-dev:amd64
  - libsensors4:amd64
  - libsoup2.4-1:amd64
  - libtag1-vanilla:amd64
  - libtag1c2a:amd64
  - libtagc0:amd64
  - libvte-common
  - libvte9
  - libx11-dev:amd64
  - libx11-doc
  - libxau-dev:amd64
  - libxcb1-dev:amd64
  - libxdmcp-dev:amd64
  - libxext-dev:amd64
  - libxfcegui4-4
  - linux-headers-3.13.0-85
  - linux-headers-3.13.0-85-generic
  - linux-image-3.13.0-85-generic
  - lm-sensors
  - m4
  - mosh
  - mousepad
  - ntp
  - p7zip-full
  - python-httplib2
  - python-ldap
  - python-pyinotify
  - python-simplejson
  - python-software-properties
  - realvnc-vnc-server
  - ristretto
  - shimmer-themes
  - tcsh
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - unzip
  - whois
  - x11proto-core-dev
  - x11proto-input-dev
  - x11proto-kb-dev
  - x11proto-xext-dev
  - xarchiver
  - xdg-utils
  - xfburn
  - xfce4
  - xfce4-artwork
  - xfce4-battery-plugin
  - xfce4-clipman
  - xfce4-clipman-plugin
  - xfce4-cpufreq-plugin
  - xfce4-cpugraph-plugin
  - xfce4-datetime-plugin
  - xfce4-dict
  - xfce4-diskperf-plugin
  - xfce4-fsguard-plugin
  - xfce4-genmon-plugin
  - xfce4-goodies
  - xfce4-mailwatch-plugin
  - xfce4-mount-plugin
  - xfce4-netload-plugin
  - xfce4-notes
  - xfce4-notes-plugin
  - xfce4-places-plugin
  - xfce4-power-manager
  - xfce4-power-manager-data
  - xfce4-quicklauncher-plugin
  - xfce4-screenshooter
  - xfce4-sensors-plugin
  - xfce4-smartbookmark-plugin
  - xfce4-systemload-plugin
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-timer-plugin
  - xfce4-verve-plugin
  - xfce4-wavelan-plugin
  - xfce4-weather-plugin
  - xfce4-xkb-plugin
  - xorg-sgml-doctools
  - xtrans-dev
  - xul-ext-ubufox
  - zsh
  - zsh-common
