#cloud-config

package_upgrade: true

yum_repos:
  epel:
    baseurl: "http://ftp.ussg.iu.edu/linux/epel/7/x86_64/"
    enabled: true
    gpgcheck: true
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    name: "Extra Packages for Enterprise Linux 7 - $basearch"
  dockerrepo:
    baseurl: "https://yum.dockerproject.org/repo/main/centos/7/"
    enabled: true
    gpgcheck: true
    gpgkey: https://yum.dockerproject.org/gpg
    name: "Docker Repository"

runcmd:
  - sysctl -w net.core.netdev_max_backlog=300000
  - sysctl -w 'net.ipv4.tcp_wmem=4096 87380 16777216'
  - sysctl -w 'net.ipv4.tcp_rmem=4096 87380 16777216'
  - sysctl -w net.core.wmem_max=16777216
  - sysctl -w net.core.rmem_max=16777216
  - [ systemctl, enable, docker.service ]
  - [ systemctl, start, docker ]

packages:
  - "@Development Tools"
  - qemu-guest-agent
  - python-virtualenv
  - python-pip
  - cmake
  - wget
  - emacs-nox
  - parted
  - cloud-utils
  - docker-engine

final_message: "The system is up, after $UPTIME seconds"
