#cloud-config

apt_update: true

apt_upgrade: true

apt_sources:
  - source: deb http://masi.vuse.vanderbilt.edu/neurodebian data main contrib non-free
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: SKS 1.1.5
      Comment: Hostname: pgp.mit.edu

      mQGiBEQ7TOgRBADvaRsIZ3VZ6Qy7PlDpdMm97m0OfvouOj/HhjOM4M3ECbGn4cYhvN1gK586
      s3sUsUcNQ8LuWvNsYhxYsVTZymCReJMEDxod0U6/z/oIbpWv5svF3kplogA66Ju/6cZx62Ri
      CSOkskI6A3Waj6xHyEo8AGOPfzbMoOOQ1TS1u9s2FwCgxziLwADvKYlDZnWM03QtqIJVD8UE
      AOks9Q2OqFoqKarj6xTRdOYIBVEp2jhozZUZmLmzpKL9E4NKGfixqxdVimFcRUGM5h7R2w7O
      RqXjCzpiPmgdv3jJLWDnmHLmMYRYQc8p5nqo8mxuO3zJugxBemWoacBDd1MJaH7nK20Hsk9L
      /jvU/qLxPJotMStTnwO+EpsKHlihA/9ZpvzR1QWNUd9nSuNR3byJhaXvxqQltsM7tLqAT4qA
      OJIcMjxr+qESdEbxNHM5M1Y21ZynrsQw+Fb1WHXNbP79vzOxHoZR0+OXe8uUpkri2d9iOocr
      e3NUdpOOJHtl6cGGTFILt8tSuOVxMT/+nlo038JQB2jARe4B85O0tkPIPbQybmV1cm8uZGVi
      aWFuLm5ldCBhcmNoaXZlIDxtaWNoYWVsLmhhbmtlQGdtYWlsLmNvbT6IRgQQEQgABgUCTVHJ
      KwAKCRCNEUVjdcAkyOvzAJ0abJz+f2a6VZG1c9T8NHMTYh1atwCgt0EE3ZZd/2in64jSzu0m
      iqhXbOKISgQQEQIACgUCSotRlwMFAXgACgkQ93+NsjFEvg8nJgCfWcdJbILBtpLZCocvOzlL
      PqJ0Fn0AoI4EpJRxoUnrtzBGUC1MqecU7WsDiGAEExECACAFAkqLUWcCGwMGCwkIBwMCBBUC
      CAMEFgIDAQIeAQIXgAAKCRCl0y8BJkmlqVklAJ4h2V6MdQkSAThF5c2Gkq6eSoIQYQCeM0DW
      yB9Bl+tTPSTYXwwZi2uoif20QmFwc3kuZ3NlLnVuaS1tYWdkZWJ1cmcuZGUgRGViaWFuIEFy
      Y2hpdmUgPG1pY2hhZWwuaGFua2VAZ21haWwuY29tPohGBBARAgAGBQJEO03FAAoJEPd/jbIx
      RL4PU18An3tn7i4qdlMi8kHbYWFoabsKc9beAJ9sl/leZNCYNMGhz+u6BQgyeLKw94heBBMR
      AgAeBQJEO0zoAhsDBgsJCAcDAgMVAgMDFgIBAh4BAheAAAoJEKXTLwEmSaWpVdoAn27DvtZi
      zNEbhz3wRUPQMiQjtqdvAJ9rS9YdPe5h5o5gHx3mw3BSkOttdYheBBMRAgAeBQJEO0zoAhsD
      BgsJCAcDAgMVAgMDFgIBAh4BAheAAAoJEKXTLwEmSaWpVdoAoLhwWL+E+2I9lrUf4Lf26quO
      K9vLAKC9ZpIF2tUirFFkBWnQvu13/TA0SokCHAQQAQIABgUCTSNBgQAKCRDAc9Iof/uem4Np
      EACQ8jxmaCaS/qk/Y4GiwLA5bvKosG3BiARZ2v5UWqCZQ1tS56yKse/lCIzXQqU9BnYW6wOI
      2rvFf9meLfd8h96peG6oKscsfbclLDIf68bBvGBQaD0VYFi/Fk/rxmTQBOCQ3AJZs8O5rIM4
      gPGE0QGvSZ1h7VRw3Uyeg4jKXLIeJn2xEmOJgt3auAR2FyKbzHaX9JCoByJZ/eU23akNl9hg
      t7ePlpXo74KNYC58auuMUhCq3BQDB+II4ERYMcmFp1N5ZG05Cl6jcaRRHDXz+Ax6DWprRI1+
      RH/Yyae6LmKpeJNwd+vM14aawnNO9h8IAQ+aJ3oYZdRhGyybbin3giJ10hmWveg/Pey91Nh9
      vBCHdDkdPU0s9zE7z/PHT0c5ccZRukxfZfkrlWQ5iqu3V064ku5f4PBy8UPSkETcjYgDnrdn
      wqIAO+oVg/SFlfsOzftnwUrvwIcZlXAgtP6MEEAs/38e/JINg4VrpdAy7HMGEUsh6Ah6lvGQ
      r+zBnG44XwKfl7e0uCYkrAzUJRGM5vx9iXvFMcMujv9EBNNBOU8/Y6MBDzGZhgaoeI27nrUv
      aveJXjAiDKAQWBLjtQjINZ8I9uaSGOul8kpbFavE4eS3+KhISrSHe4DuAa3dk9zI+FiPvXY1
      ZyfQBtNpR+gYFY6VxMbHhY1UlSLHO2eUIQLdYbRITmV1cm9EZWJpYW4gQXJjaGl2ZSBLZXkg
      PHBrZy1leHBwc3ktbWFpbnRhaW5lcnNAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iEYEEBEI
      AAYFAk1RyQYACgkQjRFFY3XAJMgEWwCggx4Gqlcrt76TSMlbU94cESo55AEAoJ3asQEMpe8t
      QUX+5aikw3z1AUoCiEoEEBECAAoFAkqf/3cDBQF4AAoJEPd/jbIxRL4PxyMAoKUIRPWlHCj/
      +HSFfwhos68wcSwmAKChuC00qutDro+AOo+uuq6YoHXj+ohgBBMRAgAgBQJKn/8bAhsDBgsJ
      CAcDAgQVAggDBBYCAwECHgECF4AACgkQpdMvASZJpalDggCeKF9KOgOPdQbFnKXl8KtHory4
      EEwAnA7jxgorE6kk2QHEXFSF8LzOOH4GiGMEExECACMCGwMGCwkIBwMCBBUCCAMEFgIDAQIe
      AQIXgAUCSp//RgIZAQAKCRCl0y8BJkmlqekFAKCRyt4+FoCzmBbRUUP3Cr8PzH++IgCgkno4
      vdjsWdyAey8e0KpITTXMFrmJAhwEEAECAAYFAk0jQYEACgkQwHPSKH/7npsFfw/+P8B8hpM3
      +T1fgboBa4R32deun8m6b8vZMXwuo/awQtMpzjem8JGXSUQm8iiX4hDtjq6ZoPrlN8T4jNmv
      iBt/F5jIJji/PYmhq+Zn9s++mfx+aF4IJrcHJWFkg/6kJzn4oSdl/YlvKf4VRCcQNtj4xV87
      GsdamnzU17XapLVMbSaVKh+6Af7ZLDerEH+iAq733HsYaTK+1xKmN7EFVXgS7bZ19C4LTzc9
      7bVHSywpT9yIrg9QQs/1kshfVIHDKyhjF6IwzSVbeGAIL3Oqo5zOMkWv7JlEIkkhTyl+FETx
      NMTMYjAk+Uei3kRodneq3YBF2uFYSEzrXQgHAyn37geiaMYjh8wu6a85nG1NS0SdxiZDIePm
      bvD9vWxFZUWYJ/h9ifsLivWcVXlvHoQ0emd+n2aiFhAck2xsuyHgnGIZMHww5IkQdu/TMqvb
      cR6d8Xulh+C4Tq7ppy+oTLADSBKII++pJQioYydRD529EUJgVlhyH27X6YAk3FuRD3zYZRYS
      2QECiKXvS665o3JRJ0ZSqNgvYOom8M0zz6bI9grnUoivMI4o7ISpE4ZwffEd37HVzmraaUHD
      XRhkulFSf1ImtXojV9nNSM5p/+9eP7OioTZhSote6Vj6Ja1SZeRkXZK7BwqPbdO0VsYOb7G/
      /ZiOlqs+paRr92G/pwBfj5Dq8EK5Ag0ERDtM9RAIAN0EJqBPvLN0tEin/y4Fe0R4n+E+zNXg
      bBsq4WidwyUFy3h/6u86FYvegXwUqVS2OsEs5MwPcCVJOfaEthF7I89QJnP9Nfx7V5I9yFB5
      3o9ii38BN7X+9gSjpfwXOvf/wIDfggxX8/wRFel37GRB7TiiABRArBezs5x+zTXvT++WPhEl
      ySj0uY8bjVR6tso+d65K0UesvAa7PPWeRS+3nhqABSFLuTTTMMbnVXCGesBrYHlFVXClAYrS
      IOX8Ub/UnuEYs9+hIV7U4jKzRF9WJhIC1cXHPmOhvleAf/I9h/0KahD7HLYud40pNBo5tW8j
      Sfp2/Q8TIE0xxshd51/xy4MAAwUH+wWnzsYVk981OKUEXul8JPyPxbw05fOd6gF4MJ3YodO+
      6dfoyIl3bewk+11KXZQALKaO1xmkAEO1RqizPeetoadBVkQBp5xPudsVElUTOX0pTYhkUd3i
      BilsCYKK1/KQ9KzDI+O/lRsm6L9lc6rV0IgPU00P4BAwR+x8Rw7TJFbuS0miR3lP1NSguz+/
      kpjxzmGPLyHJ+LVDYFkk6t0jPXhqFdUY6McUTBDEvavTGlVO062l9APTmmSMVFDsPN/rBes2
      rYhuuT+lDp+gcaS1UoaYCIm9kKOteQBnowX9V74Z+HKEYLtwILaSnNe6/fNSTvyjg0z+R+sP
      CY4nHewbVC+ISQQYEQIACQUCRDtM9QIbDAAKCRCl0y8BJkmlqbecAJ9BUdSKVg9H+fQNyP5s
      bOjj4RDtdACfXHrRHa2+XjJP0dhpvJ8IfvYnQsU=
      =fAJZ
      -----END PGP PUBLIC KEY BLOCK-----
  - source: deb http://masi.vuse.vanderbilt.edu/neurodebian trusty main contrib non-free
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: SKS 1.1.5
      Comment: Hostname: pgp.mit.edu

      mQGiBEQ7TOgRBADvaRsIZ3VZ6Qy7PlDpdMm97m0OfvouOj/HhjOM4M3ECbGn4cYhvN1gK586
      s3sUsUcNQ8LuWvNsYhxYsVTZymCReJMEDxod0U6/z/oIbpWv5svF3kplogA66Ju/6cZx62Ri
      CSOkskI6A3Waj6xHyEo8AGOPfzbMoOOQ1TS1u9s2FwCgxziLwADvKYlDZnWM03QtqIJVD8UE
      AOks9Q2OqFoqKarj6xTRdOYIBVEp2jhozZUZmLmzpKL9E4NKGfixqxdVimFcRUGM5h7R2w7O
      RqXjCzpiPmgdv3jJLWDnmHLmMYRYQc8p5nqo8mxuO3zJugxBemWoacBDd1MJaH7nK20Hsk9L
      /jvU/qLxPJotMStTnwO+EpsKHlihA/9ZpvzR1QWNUd9nSuNR3byJhaXvxqQltsM7tLqAT4qA
      OJIcMjxr+qESdEbxNHM5M1Y21ZynrsQw+Fb1WHXNbP79vzOxHoZR0+OXe8uUpkri2d9iOocr
      e3NUdpOOJHtl6cGGTFILt8tSuOVxMT/+nlo038JQB2jARe4B85O0tkPIPbQybmV1cm8uZGVi
      aWFuLm5ldCBhcmNoaXZlIDxtaWNoYWVsLmhhbmtlQGdtYWlsLmNvbT6IRgQQEQgABgUCTVHJ
      KwAKCRCNEUVjdcAkyOvzAJ0abJz+f2a6VZG1c9T8NHMTYh1atwCgt0EE3ZZd/2in64jSzu0m
      iqhXbOKISgQQEQIACgUCSotRlwMFAXgACgkQ93+NsjFEvg8nJgCfWcdJbILBtpLZCocvOzlL
      PqJ0Fn0AoI4EpJRxoUnrtzBGUC1MqecU7WsDiGAEExECACAFAkqLUWcCGwMGCwkIBwMCBBUC
      CAMEFgIDAQIeAQIXgAAKCRCl0y8BJkmlqVklAJ4h2V6MdQkSAThF5c2Gkq6eSoIQYQCeM0DW
      yB9Bl+tTPSTYXwwZi2uoif20QmFwc3kuZ3NlLnVuaS1tYWdkZWJ1cmcuZGUgRGViaWFuIEFy
      Y2hpdmUgPG1pY2hhZWwuaGFua2VAZ21haWwuY29tPohGBBARAgAGBQJEO03FAAoJEPd/jbIx
      RL4PU18An3tn7i4qdlMi8kHbYWFoabsKc9beAJ9sl/leZNCYNMGhz+u6BQgyeLKw94heBBMR
      AgAeBQJEO0zoAhsDBgsJCAcDAgMVAgMDFgIBAh4BAheAAAoJEKXTLwEmSaWpVdoAn27DvtZi
      zNEbhz3wRUPQMiQjtqdvAJ9rS9YdPe5h5o5gHx3mw3BSkOttdYheBBMRAgAeBQJEO0zoAhsD
      BgsJCAcDAgMVAgMDFgIBAh4BAheAAAoJEKXTLwEmSaWpVdoAoLhwWL+E+2I9lrUf4Lf26quO
      K9vLAKC9ZpIF2tUirFFkBWnQvu13/TA0SokCHAQQAQIABgUCTSNBgQAKCRDAc9Iof/uem4Np
      EACQ8jxmaCaS/qk/Y4GiwLA5bvKosG3BiARZ2v5UWqCZQ1tS56yKse/lCIzXQqU9BnYW6wOI
      2rvFf9meLfd8h96peG6oKscsfbclLDIf68bBvGBQaD0VYFi/Fk/rxmTQBOCQ3AJZs8O5rIM4
      gPGE0QGvSZ1h7VRw3Uyeg4jKXLIeJn2xEmOJgt3auAR2FyKbzHaX9JCoByJZ/eU23akNl9hg
      t7ePlpXo74KNYC58auuMUhCq3BQDB+II4ERYMcmFp1N5ZG05Cl6jcaRRHDXz+Ax6DWprRI1+
      RH/Yyae6LmKpeJNwd+vM14aawnNO9h8IAQ+aJ3oYZdRhGyybbin3giJ10hmWveg/Pey91Nh9
      vBCHdDkdPU0s9zE7z/PHT0c5ccZRukxfZfkrlWQ5iqu3V064ku5f4PBy8UPSkETcjYgDnrdn
      wqIAO+oVg/SFlfsOzftnwUrvwIcZlXAgtP6MEEAs/38e/JINg4VrpdAy7HMGEUsh6Ah6lvGQ
      r+zBnG44XwKfl7e0uCYkrAzUJRGM5vx9iXvFMcMujv9EBNNBOU8/Y6MBDzGZhgaoeI27nrUv
      aveJXjAiDKAQWBLjtQjINZ8I9uaSGOul8kpbFavE4eS3+KhISrSHe4DuAa3dk9zI+FiPvXY1
      ZyfQBtNpR+gYFY6VxMbHhY1UlSLHO2eUIQLdYbRITmV1cm9EZWJpYW4gQXJjaGl2ZSBLZXkg
      PHBrZy1leHBwc3ktbWFpbnRhaW5lcnNAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iEYEEBEI
      AAYFAk1RyQYACgkQjRFFY3XAJMgEWwCggx4Gqlcrt76TSMlbU94cESo55AEAoJ3asQEMpe8t
      QUX+5aikw3z1AUoCiEoEEBECAAoFAkqf/3cDBQF4AAoJEPd/jbIxRL4PxyMAoKUIRPWlHCj/
      +HSFfwhos68wcSwmAKChuC00qutDro+AOo+uuq6YoHXj+ohgBBMRAgAgBQJKn/8bAhsDBgsJ
      CAcDAgQVAggDBBYCAwECHgECF4AACgkQpdMvASZJpalDggCeKF9KOgOPdQbFnKXl8KtHory4
      EEwAnA7jxgorE6kk2QHEXFSF8LzOOH4GiGMEExECACMCGwMGCwkIBwMCBBUCCAMEFgIDAQIe
      AQIXgAUCSp//RgIZAQAKCRCl0y8BJkmlqekFAKCRyt4+FoCzmBbRUUP3Cr8PzH++IgCgkno4
      vdjsWdyAey8e0KpITTXMFrmJAhwEEAECAAYFAk0jQYEACgkQwHPSKH/7npsFfw/+P8B8hpM3
      +T1fgboBa4R32deun8m6b8vZMXwuo/awQtMpzjem8JGXSUQm8iiX4hDtjq6ZoPrlN8T4jNmv
      iBt/F5jIJji/PYmhq+Zn9s++mfx+aF4IJrcHJWFkg/6kJzn4oSdl/YlvKf4VRCcQNtj4xV87
      GsdamnzU17XapLVMbSaVKh+6Af7ZLDerEH+iAq733HsYaTK+1xKmN7EFVXgS7bZ19C4LTzc9
      7bVHSywpT9yIrg9QQs/1kshfVIHDKyhjF6IwzSVbeGAIL3Oqo5zOMkWv7JlEIkkhTyl+FETx
      NMTMYjAk+Uei3kRodneq3YBF2uFYSEzrXQgHAyn37geiaMYjh8wu6a85nG1NS0SdxiZDIePm
      bvD9vWxFZUWYJ/h9ifsLivWcVXlvHoQ0emd+n2aiFhAck2xsuyHgnGIZMHww5IkQdu/TMqvb
      cR6d8Xulh+C4Tq7ppy+oTLADSBKII++pJQioYydRD529EUJgVlhyH27X6YAk3FuRD3zYZRYS
      2QECiKXvS665o3JRJ0ZSqNgvYOom8M0zz6bI9grnUoivMI4o7ISpE4ZwffEd37HVzmraaUHD
      XRhkulFSf1ImtXojV9nNSM5p/+9eP7OioTZhSote6Vj6Ja1SZeRkXZK7BwqPbdO0VsYOb7G/
      /ZiOlqs+paRr92G/pwBfj5Dq8EK5Ag0ERDtM9RAIAN0EJqBPvLN0tEin/y4Fe0R4n+E+zNXg
      bBsq4WidwyUFy3h/6u86FYvegXwUqVS2OsEs5MwPcCVJOfaEthF7I89QJnP9Nfx7V5I9yFB5
      3o9ii38BN7X+9gSjpfwXOvf/wIDfggxX8/wRFel37GRB7TiiABRArBezs5x+zTXvT++WPhEl
      ySj0uY8bjVR6tso+d65K0UesvAa7PPWeRS+3nhqABSFLuTTTMMbnVXCGesBrYHlFVXClAYrS
      IOX8Ub/UnuEYs9+hIV7U4jKzRF9WJhIC1cXHPmOhvleAf/I9h/0KahD7HLYud40pNBo5tW8j
      Sfp2/Q8TIE0xxshd51/xy4MAAwUH+wWnzsYVk981OKUEXul8JPyPxbw05fOd6gF4MJ3YodO+
      6dfoyIl3bewk+11KXZQALKaO1xmkAEO1RqizPeetoadBVkQBp5xPudsVElUTOX0pTYhkUd3i
      BilsCYKK1/KQ9KzDI+O/lRsm6L9lc6rV0IgPU00P4BAwR+x8Rw7TJFbuS0miR3lP1NSguz+/
      kpjxzmGPLyHJ+LVDYFkk6t0jPXhqFdUY6McUTBDEvavTGlVO062l9APTmmSMVFDsPN/rBes2
      rYhuuT+lDp+gcaS1UoaYCIm9kKOteQBnowX9V74Z+HKEYLtwILaSnNe6/fNSTvyjg0z+R+sP
      CY4nHewbVC+ISQQYEQIACQUCRDtM9QIbDAAKCRCl0y8BJkmlqbecAJ9BUdSKVg9H+fQNyP5s
      bOjj4RDtdACfXHrRHa2+XjJP0dhpvJ8IfvYnQsU=
      =fAJZ
      -----END PGP PUBLIC KEY BLOCK-----    
    
packages:
  - qemu-guest-agent
  - afni
  - afni-atlases
  - afni-common
  - ants
  - aspell
  - aspell-en
  - autoconf
  - automake
  - autotools-dev
  - dc
  - debhelper
  - dh-apparmor
  - environment-modules
  - fail2ban
  - firefox
  - fonts-lyx
  - freeglut3:amd64
  - fsl-5.0-complete
  - fsl-5.0-core
  - fsl-5.0-eddy-nonfree
  - fsl-atlases
  - fsl-bangor-cerebellar-atlas
  - fsl-first-data
  - fsl-harvard-oxford-atlases
  - fsl-harvard-oxford-cortical-lateralized-atlas
  - fsl-jhu-dti-whitematter-atlas
  - fsl-juelich-histological-atlas
  - fsl-mni-structural-atlas
  - fsl-mni152-templates
  - fsl-oxford-striatal-atlas
  - fsl-oxford-thalamic-connectivity-atlas
  - fsl-possum-data
  - fsl-resting-connectivity-parcellation-atlases
  - fsl-subthalamic-nucleus-atlas
  - fsl-talairach-daemon-atlas
  - fslview
  - fslview-doc
  - gettext
  - ghostscript
  - gifsicle
  - glib-networking-common
  - glib-networking-services
  - glib-networking:amd64
  - gnome-icon-theme
  - gnome-icon-theme-full
  - gsettings-desktop-schemas
  - gsfonts
  - gtk2-engines-murrine:amd64
  - gtk2-engines-pixbuf:amd64
  - hddtemp
  - intltool-debian
  - isc-dhcp-server
  - javascript-common
  - language-pack-en
  - language-pack-en-base
  - libamd2.3.1:amd64
  - libaspell15
  - libasprintf-dev:amd64
  - libaudio2:amd64
  - libavcodec54:amd64
  - libavformat54:amd64
  - libavutil52:amd64
  - libblas3
  - libburn4
  - libcamd2.3.1:amd64
  - libccolamd2.8.0:amd64
  - libcharls1
  - libcholmod2.1.2:amd64
  - libcolamd2.8.0:amd64
  - libcr0
  - libcupsfilters1:amd64
  - libcupsimage2:amd64
  - libdbusmenu-glib4:amd64
  - libdbusmenu-gtk4:amd64
  - libexpat1-dev:amd64
  - libf2c2
  - libfam0
  - libfftw3-double3:amd64
  - libfile-basedir-perl
  - libfile-desktopentry-perl
  - libfile-mimeinfo-perl
  - libgdchart-gd2-noxpm
  - libgdcm2.2
  - libgettextpo-dev:amd64
  - libgettextpo0:amd64
  - libgfortran3:amd64
  - libgiftiio0
  - libgl2ps0
  - libglw1-mesa:amd64
  - libgs9
  - libgs9-common
  - libgsl0ldbl
  - libgsm1:amd64
  - libgtksourceview2.0-0
  - libgtksourceview2.0-common
  - libgts-0.7-5
  - libgts-bin
  - libhdf5-7:amd64
  - libhwloc-plugins
  - libhwloc5:amd64
  - libibverbs1
  - libijs-0.35
  - libinsighttoolkit4.7
  - libisofs6
  - libjbig2dec0
  - libjs-excanvas
  - libjs-jquery
  - libjte1
  - liblapack3
  - libmail-sendmail-perl
  - libmotif-common
  - libmp3lame0:amd64
  - libmrm4:amd64
  - libmysqlclient18:amd64
  - libnetcdfc++4
  - libnetcdfc7
  - libnetpbm10
  - libnewmat10ldbl
  - libnifti2
  - libopenjpeg2:amd64
  - libopenmpi1.6
  - libopts25:amd64
  - libopus0
  - libpango1.0-0:amd64
  - libpangox-1.0-0:amd64
  - libpangoxft-1.0-0:amd64
  - libpaper-utils
  - libpaper1:amd64
  - libpq5
  - libprotobuf8:amd64
  - libproxy1:amd64
  - libpthread-stubs0-dev:amd64
  - libpython-dev:amd64
  - libpython2.7-dev:amd64
  - libqhull6:amd64
  - libqt4-dbus:amd64
  - libqt4-declarative:amd64
  - libqt4-designer:amd64
  - libqt4-network:amd64
  - libqt4-qt3support:amd64
  - libqt4-script:amd64
  - libqt4-sql-mysql:amd64
  - libqt4-sql:amd64
  - libqt4-svg:amd64
  - libqt4-xml:amd64
  - libqt4-xmlpatterns:amd64
  - libqtcore4:amd64
  - libqtdbus4:amd64
  - libqtgui4:amd64
  - libqwt5-qt4
  - libschroedinger-1.0-0:amd64
  - libsensors4:amd64
  - libsoup2.4-1:amd64
  - libspeex1:amd64
  - libsvm3
  - libswscale2:amd64
  - libsys-hostname-long-perl
  - libtag1-vanilla:amd64
  - libtag1c2a:amd64
  - libtagc0:amd64
  - libtcl8.6:amd64
  - libtk8.6:amd64
  - libtorque2
  - libuil4:amd64
  - libumfpack5.6.2:amd64
  - libunistring0:amd64
  - libva1:amd64
  - libvolpack1
  - libvte-common
  - libvte9
  - libvtk5.8
  - libvtk5.8-qt4
  - libwebp5:amd64
  - libwebpmux1:amd64
  - libx11-dev:amd64
  - libx11-doc
  - libx264-142:amd64
  - libxau-dev:amd64
  - libxcb1-dev:amd64
  - libxdmcp-dev:amd64
  - libxext-dev:amd64
  - libxfcegui4-4
  - libxm4:amd64
  - libxss1:amd64
  - libxvidcore4:amd64
  - linux-headers-3.13.0-85
  - linux-headers-3.13.0-85-generic
  - linux-image-3.13.0-85-generic
  - lm-sensors
  - m4
  - matlab-spm8
  - matlab-support
  - mosh
  - mousepad
  - mysql-common
  - netpbm
  - neurodebian-popularity-contest
  - nifti-bin
  - ntp
  - ocl-icd-libopencl1:amd64
  - p7zip-full
  - po-debconf
  - poppler-data
  - python-cairo
  - python-dateutil
  - python-decorator
  - python-dev
  - python-dicom
  - python-fuse
  - python-future
  - python-glade2
  - python-gobject-2
  - python-gtk2
  - python-httplib2
  - python-imaging
  - python-joblib
  - python-ldap
  - python-libsvm
  - python-matplotlib
  - python-matplotlib-data
  - python-mdp
  - python-nibabel
  - python-nose
  - python-numpy
  - python-pil
  - python-pp
  - python-py
  - python-pyinotify
  - python-pyparsing
  - python-pytest
  - python-scipy
  - python-simplejson
  - python-sklearn
  - python-sklearn-lib
  - python-software-properties
  - python-support
  - python-tk
  - python-tz
  - python2.7-dev
  - qdbus
  - qhull-bin
  - qt-assistant-compat
  - qtchooser
  - qtcore4-l10n
  - realvnc-vnc-server
  - ristretto
  - shimmer-themes
  - sispmctl
  - spm8-common
  - spm8-data
  - spm8-doc
  - tcl
  - tcl8.6
  - tcsh
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - tk
  - tk8.6
  - unzip
  - whois
  - x11proto-core-dev
  - x11proto-input-dev
  - x11proto-kb-dev
  - x11proto-xext-dev
  - xarchiver
  - xdg-utils
  - xfburn
  - xfce4
  - xfce4-artwork
  - xfce4-battery-plugin
  - xfce4-clipman
  - xfce4-clipman-plugin
  - xfce4-cpufreq-plugin
  - xfce4-cpugraph-plugin
  - xfce4-datetime-plugin
  - xfce4-dict
  - xfce4-diskperf-plugin
  - xfce4-fsguard-plugin
  - xfce4-genmon-plugin
  - xfce4-goodies
  - xfce4-mailwatch-plugin
  - xfce4-mount-plugin
  - xfce4-netload-plugin
  - xfce4-notes
  - xfce4-notes-plugin
  - xfce4-places-plugin
  - xfce4-power-manager
  - xfce4-power-manager-data
  - xfce4-quicklauncher-plugin
  - xfce4-screenshooter
  - xfce4-sensors-plugin
  - xfce4-smartbookmark-plugin
  - xfce4-systemload-plugin
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-timer-plugin
  - xfce4-verve-plugin
  - xfce4-wavelan-plugin
  - xfce4-weather-plugin
  - xfce4-xkb-plugin
  - xmhtml1:amd64
  - xorg-sgml-doctools
  - xtrans-dev
  - xul-ext-ubufox
  - zsh
  - zsh-common
